apiVersion: v1
kind: Service
metadata:
  name: leapapp-app-service
  namespace: leapapp
  labels:
    app: leapapp-app
spec:
  type: ClusterIP
  selector:
    app: leapapp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
