apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-flask-app.fullname" . }}-secret
  labels:
    app: {{ include "my-flask-app.name" . }}
type: Opaque
data:
  db-user: {{ .Values.secrets.dbUser | b64enc }}
  db-pass: {{ .Values.secrets.dbPass | b64enc }}
